name: Create HTML files

on:
  push:
    branches: [main]
    paths:
      - 'articles/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: EndBug/add-and-commit@v7
        with:
          add: 'blogs'
          author_name: Tapio Salonen
          author_email: tsa.dom@pm.me
          branch: main
          branch_mode: create
          message: 'Created files'
