name: Create HTML files

on:
  push:
    branches: [main]
    paths:
      - 'articles/**'
      - 'pages/**'
      - '.github/workflows/**'

jobs:
  html-files:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: bash build.bash
      - uses: EndBug/add-and-commit@v7
        with:
          author_name: Tapio Salonen
          author_email: tsa.dom@pm.me
          branch: main
          branch_mode: create
          message: 'Created files'
