name: Create HTML files

on:
  push:
    branches: [main]

jobs:
  html-files:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: bash build.bash
      - uses: EndBug/add-and-commit@v7
        with:
          author_name: Tapio Salonen
          author_email: tsa.dom@pm.me
          branch: main
          branch_mode: create
          message: 'Created files'

  publish:
    runs-on: ubuntu-latest
    needs: [html-files]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Push blogs to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'blogs'
          destination-github-username: 'tsa-dom'
          destination-repository-name: 'tsa-dom.github.io'
          user-email: tsa.dom@pm.me
          target-branch: gh-pages
          target-directory: 'blogs'
      - name: Push pages to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'html'
          destination-github-username: 'tsa-dom'
          destination-repository-name: 'tsa-dom.github.io'
          user-email: tsa.dom@pm.me
          target-branch: gh-pages
          target-directory: 'pages'
