name: Publish changes

on:
  push:
    branches: [main]
    paths:
      - 'blogs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'blogs'
          destination-github-username: 'tsa-dom'
          destination-repository-name: 'gh-pages'
          user-email: tsa.dom@pm.me
          target-branch: gh-pages
          target-directory: 'blogs'